version: 2
executorType: machine
stages:
  build:
    workDir: ~/docker.nginx-php-fpm
    steps:
      - checkout

      - run: make container

      - run:
          shell: /bin/bash
          command: make test
          name: make test
