FROM UPSTREAM_REPO

ARG NGINX_VERSION=1.11.8-1~jessie
ENV NGINX_VERSION=$NGINX_VERSION
ARG DRUSH_VERSION=8.1.12
ENV DRUSH_VERSION=$DRUSH_VERSION
ARG WP_CLI_VERSION=1.2.1
ENV WP_CLI_VERSION=$WP_CLI_VERSION

ENV PATH="/root/.composer/vendor/bin:$PATH"

RUN wget -q -O /tmp/nginx_signing.key http://nginx.org/keys/nginx_signing.key
RUN apt-key add /tmp/nginx_signing.key
RUN echo "deb http://nginx.org/packages/mainline/debian/ jessie nginx" >> /etc/apt/sources.list && \
	apt-get -qq update && \
	apt-get -qq install --no-install-recommends --no-install-suggests -y \
        nginx=${NGINX_VERSION} \
        libcap2-bin \
        supervisor sudo && \
    apt-get -qq clean -y && \
	rm -rf /var/lib/apt/lists/* && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer

ADD "https://github.com/drush-ops/drush/releases/download/$DRUSH_VERSION/drush.phar" /usr/bin/drush
ADD "https://github.com/wp-cli/wp-cli/releases/download/v${WP_CLI_VERSION}/wp-cli-${WP_CLI_VERSION}.phar" /usr/bin/wp-cli

ADD files /
ADD ./bin/linux/git-sync /usr/bin/git-sync

RUN rm /etc/php/7.0/cli/php.ini && \
    ln -s /etc/php/7.0/fpm/php.ini /etc/php/7.0/cli/php.ini && \
    mkdir -p /etc/nginx/sites-enabled && \
    ln -s /etc/nginx/sites-available/default.conf /etc/nginx/sites-enabled/default.conf && \
    touch /var/log/php7.0-fpm.log && \
    chown nginx:nginx /var/log/php7.0-fpm.log && \
    chown -R nginx:nginx /var/run && \
    touch /var/log/nginx/access.log && \
    touch /var/log/nginx/error.log && \
    chown -R nginx:nginx /var/log/nginx/ && \
    mkdir -p /var/lib/nginx/logs && \
    touch /var/lib/nginx/logs/error.log && \
    chown nginx:nginx /var/lib/nginx/logs/error.log && \
    chmod ugo+x /usr/bin/* && \
    chmod ugo+x /start.sh

EXPOSE 80 443

HEALTHCHECK CMD curl --fail http://localhost/healthcheck/ || exit 1

CMD ["/start.sh"]
